### REFRESH LOCAL 
POST http://localhost:5000/api/auth/refresh
content-type: application/json

{
    "refreshToken": "42a3c8b1-c80a-4cde-8582-f2298542af16"
}

### REGISTER LOCAL EMAIL
POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "email": "ponomarykov5@gmail.com", 
    "password": "12345678"
}

### LOGIN LOCAL EMAIL
POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "ponomarykov5@gmail.com", 
    "password": "12345678"
}

### LOGIN LOCAL ID
POST http://localhost:5000/api/login
content-type: application/json

{
    "id": "id",
    "email": "ponomarykov@gmail.com"
}


POST https://pure-anchorage-45021.herokuapp.com/api/login
content-type: application/json

{
    "id":"id"
}



POST https://pure-anchorage-45021.herokuapp.com/api/register
content-type: application/json

{
    "id": "id"
}
